### ISSUE TITLE
Issue when accessing endpoint that redirects to oauth provider

### ISSUE THREAD

**Issue by semenodp** [elbywan/wretch#101]
Currently, I am trying to call the backend endpoint that would redirect me to oauth provider using the following code
```
wretch(`http://localhost:8080/auth/google`)
      .options({ mode: 'no-cors', credentials: 'include', redirect: 'follow' })
      .get();
```
However, once the backend responds with 200, I get the following error in console.log
```
throwingPromise resolver.js:41
    promise callback*resolver/throwingPromise< resolver.js:39
    promise callback*resolver resolver.js:36
    method wretcher.js:217
    get wretcher.js:223
```
Any ideas on how to potentially debug this issue? I tried to follow the error trace but the error does not seem to be informative

**Comment by elbywan** [comment]
Hi @semenodp,

> Any ideas on how to potentially debug this issue? 

Yes, you could add a `.catch` call to catche the error thrown by the promise.

```js
wretch(`http://localhost:8080/auth/google`)
      .options({ mode: 'no-cors', credentials: 'include', redirect: 'follow' })
      .get()
      .res(console.log)
      .catch(console.error)
```

**Comment by semenodp** [comment]
I actually tried to do that, and I got the same error just in the string format

**Comment by elbywan** [comment]
Can you check the `network` tab in the developer tools to monitor the requests/responses?

**Comment by elbywan** [comment]
Actually I think I know what the issue is, using mode `no-cors` marks the response as "opaque" which is considered as "not ok" (`response.ok` is `false`). This is the reason why `wretch` throws an error.

You can inspect the response by using `error.response`:

```ts
wretch(`http://localhost:8080/auth/google`)
  .options({ mode: 'no-cors', credentials: 'include', redirect: 'follow' })
  .get()
  .res(console.log)
  .catch(error => console.error(error.response))
```

Are you sure that you need the `no-cors` mode?

**Comment by semenodp** [comment]
Thanks @elbywan, I see the error now. I am actually not sure about `no-cors` mode. I have tried using with `cors` mode but I keep on getting `Reason: CORS header ‘Access-Control-Allow-Origin’ missing` from redirect request to google oauth, but wretch seems to be sending it to my backend (I can see it as header in network tab)

**Comment by elbywan** [comment]
> Reason: CORS header ‘Access-Control-Allow-Origin’ missing from redirect request to google oauth, but wretch seems to be sending it to my backend

`Access-Control-Allow-Origin` is a server-side header that, when set, allows cross-origin requests. Here is a good [article](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) that explains in detail how this is working.

So if I understand correctly, you are calling `http://localhost:8080/auth/google` that in turn redirects the request to `https://oauth/server/path` which does not support cross domain requests.

And the following error gets thrown because the header is missing:

```
Access to fetch at 'https://oauth/server/path' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

But then I'm just not sure about what you are trying to achieve:

- If you want to access the oauth server from the localhost domain, then querying from the browser and reading the response will not be possible. As a workaround, if you really need to query the oauth server and get the body you could do that from your localhost server instead since CORS rules only restrict browser requests.

- If you are simply trying to redirect the client to the oauth server, then `window.location =  "http://localhost:8080/auth/google" should be enough.

**Comment by semenodp** [comment]
Thank you so much for detailed explanation. I indeed did not quite understand how the oauth authentication works with SPA on frontend and backend serving at different origins, therefore was trying to achieve impossible. 

As of right now, I am trying to query the oauth server directly from frontend as described [here](https://developers.google.com/identity/protocols/oauth2/javascript-implicit-flow#oauth-2.0-endpoints_2) using the following code

```js
let oauth2Endpoint = 'https://accounts.google.com/o/oauth2/v2/auth';
    wretch(oauth2Endpoint)
      .query({
        client_id: clientID,
        redirect_uri: 'http://localhost:5000',
        response_type: 'token',
        scope: 'profile',
        include_granted_scopes: 'true',
        state: 'pass-through value',
      })
      .headers({
        'Access-Control-Allow-Origin': 'http://localhost:5000',
        'Access-Control-Allow-Methods': 'POST, GET, OPTIONS, PUT, DELETE',
        'Access-Control-Allow-Credentials': 'true',
        'Access-Control-Allow-Headers':
          'Accept, Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization',
      })
      .options({ redirect: 'follow' })
      .get()
```
but I keep getting the same error `(Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

Am I setting the headers incorrectly? I also have tried to use `mode: cors` but that did not help

**Comment by elbywan** [comment]
> As of right now, I am trying to query the oauth server directly from frontend as described here

Well this does not look like an http query but a full client location redirection.

As far as I understand the flow is:

1- Redirect the user to the `https://accounts.google.com/o/oauth2/v2/auth` url with the proper options. (there is a sample code in the page using a form)
2- Log in with a Google Account.
3- The user is redirected to the url you specified with the `redirect_uri=xxx` query parameter.

> Am I setting the headers incorrectly? I also have tried to use mode: cors but that did not help

Querying the `https://accounts.google.com` server (and reading the response) is impossible from a browser because the google endpoint does not allow cross origin requests (except from the `myaccount.google.com` domain).

Using wretch or any other http client seem unnecessary for this use case. You should just redirect the client to the oauth page using the example provided in the Google OAuth tutorial or by calling `window.location = "https://accounts.google.com/o/oauth2/v2/auth?…"`.

I'm going to close the issue since it looks unrelated to this library.
