### ISSUE TITLE
unable to post image via wretch

### ISSUE THREAD

**Issue by hieunm22** [elbywan/wretch#102]
I'm new in wretch
Before using wretch, i used axios to handle my api calls
When using normal request using get (with parameters, query string), post (with body), everything is fine until I use to post formData using wretch
here's my code using axios and wretch to post my file to API
axios
```
const uploadAvatarAxios = (options, form) => axios.post('https://localhost:44387/api/account/changeavatar', form, options)
            .then(uploadAvatarCallback)
            .catch(handleError)
```

and wretch

```
const uploadAvatar = (options, form) => wretch('https://localhost:44387/api').url('/account/changeavatar')
            .auth(options.headers.Authorization)
            .post(form)
            .json(uploadAvatarCallback)
            .catch(handleError)
```

and here's my headers and form defination

```
const token = getToken()
formData.append("File", e.currentTarget.files[0])  // from input type=file
formData.append("UserId", 1)  // hard code here
const options = {
  headers: {
    "Content-Type": "multipart/form-data",
    Authorization: `Bearer ${token}`
  }
}
```

My issue is with using axios code, it called successfully to API with form value appended, but the wretch one didn't receive value appended
Could you help me to use wretch to post file to API
Thanks

**Comment by elbywan** [comment]
Hi @hieunm22,

I think that instead of using `.post(form)` and setting the headers manually you should try using the [`.formData`](https://github.com/elbywan/wretch#formdataformobject-object-recursive-string--boolean--false) helper because `.post(form)` will try to serialize the form object to JSON.

Something like:

```js
.formData({
  File: e.currentTarget.files[0],
  UserId: 1
})
.post()
```

Another option would be to use the `.body` method with the form object if you want to manage the headers and FormData object manually:

```js
.body(form)
.post()
```

I will mark this issue as a duplicate since issue #71 is basically the same question.

**Comment by hieunm22** [comment]
thanks for your reply. i'll try your suggestion
