### ISSUE TITLE
Is there a way to register a global catcher/globally handle errors

### ISSUE THREAD

**Issue by curtisy1** [elbywan/wretch#103]
First of all, thanks for making wretcher!

We're currently trying to configure error handling when a server responds with non-success status codes. However adding an `unauthorized(...)` or `catcher()` method for every `wretch()` call seems a bit tedious so I was wondering if there's something like a global error handler that could be registered once and do the same thing everywhere.

I see the comment above the `catcher` method states "Adds a default catcher which will be called on every subsequent request when the error code matches" but that doesn't seem to meet the requirements.

What we tried so far is using 
`wretch().catcher(401, err => console.log('Unauthorized')).defaults({'X-Requested-With': 'XMLHttpRequest'})` but the next call to `wretch('some/url).get().json()` still results in an exception when a 401 is returned.

Is there another way to register an exception handler/catcher once and have it used anywhere and I'm just missing something or would I have to configure a default wretcher object that I export and use instead of always instantiating a new one?

**Comment by elbywan** [comment]
Hi @curtisy1,

> First of all, thanks for making wretcher!

Thanks! ❤️ 

> Is there another way to register an exception handler/catcher once and have it used anywhere and I'm just missing something or would I have to configure a default wretcher object that I export and use instead of always instantiating a new one?

Yes this is correct, there is  no way to register a global handler, since almost every method will return a fresh immutable instance with the added configuration. But exporting a global object should roughly be equivalent.

`.defaults` `.polyfills` and `.errorType` and the only methods that will impact every instance.

> I see the comment above the catcher method states "Adds a default catcher which will be called on every subsequent request when the error code matches" but that doesn't seem to meet the requirements.

Well it is implied that it will catch every subsequent requests *made with the same wretch instance or instances based on the one configured with the catcher*.  I understand that it might not be obvious, I'll think about rewording the documentation.

So to make it work, you need to instantiate and export a "default" wretcher instance that will then be used as a base throughout the application.

```javascript
export const baseWretch = wretch("https://httpstat.us").catcher(401, err => console.log('Caught'))

/* ... */

// use "baseWretch", not "wretch()" otherwise it will return a fresh instance.
baseWretch.url("/401").get().text(console.log)

// -> prints "Caught"
```

**Comment by curtisy1** [comment]
Thanks for the quick reply @elbywan
Closing this as my question has been answered 🙂
