### ISSUE TITLE
Usage with `no-cors`

### ISSUE THREAD

**Issue by ynnirc** [elbywan/wretch#121]
I would like to use wretch with the `no-cors` mode. I do not control the server yet I absolutely have to make a request. Whenever I make a request with this mode, this is the error I get:
```
Uncaught (in promise) Error
    at resolver.js:41
```
Here is what I am currently doing to avoid the error:
```javascript
wretch('http://example.com', {mode: 'no-cors'})
     .post({test: '123'})
     .res()
     .catch(err => {});
```
Since there will never be a response for a `no-cors` request, having to use `res` doesn't make much sense. It would be great if it would be possible to handle the error with the `fetchError` catcher.

**Comment by elbywan** [comment]
Hey @ynnirc,

Thanks for reporting the issue!

> Whenever I make a request with this mode, this is the error I get

So this error is thrown because for opaque responses the `response.ok` status is false. Then `wretch` tries to call the `response.text()` helper to read the body and populate the error message, which is not possible with this kind of response.

This is an issue, and I'll add some code to treat opaque responses differently and make an explicit error message that states why the error has been thrown.

> Since there will never be a response for a no-cors request, having to use res doesn't make much sense. 

Well calling `res()` is needed to actually perform the request, this in inherent to the way wretch works under the hood.

> It would be great if it would be possible to handle the error with the fetchError catcher.

I wrote `fetchError` to handle network errors and other error thrown synchronously. This error is actually thrown after the request has been resolved, so I don't think that it would fit in there.
