### ISSUE TITLE
send a string in a post request

### ISSUE THREAD

**Issue by ahtd3** [elbywan/wretch#130]
I'm new in wretch
When using a post request with body, everything works fine to me
```js
const postRequest = (clientId: string) => request.url(EP.postRequest)
            .post({ clientId })
            .json(handleResponse)
            .catch(handleError)
```
but if I want to send a string only (`.post(clientId)`) instead of creating a new model like above (`post({ clientId })`)
```js
const postRequest = (clientId: string) => request.url(EP.postRequest)
            .post(clientId)
            .json(handleResponse)
            .catch(handleError)
```
the backend responses a 415 response status code

here's what I defined to API endpoint in backend (using dotnet core)

``` cs
[HttpPost("PostRequest")]
public async Task<bool> PostRequest(string clientId) {  }
```

so what was I wrong in my code?
please give me any explain.
thanks

**Comment by elbywan** [comment]
Hey @ahtd3,

I do not see anything wrong regarding the `wretch` code:

```js
wretch()
    .url("/")
    .post("hello")
    .text(console.log)
    .catch(console.error)
```

<img width="131" alt="Capture d’écran 2022-04-18 à 19 53 34" src="https://user-images.githubusercontent.com/3428394/163851365-6305c42c-8210-4aff-b6b8-1adf1141f70e.png">

I assume that the issue comes from the `.net` code, so I will close the issue since it is not related to the library.
