### ISSUE TITLE
Issues with type inference on method .res

### ISSUE THREAD

**Issue by giulianovarriale** [elbywan/wretch#143]
Hello. First, thanks for creating this package. Awesome job!

I was creating a service to perform a request and based on the success status, do something else.
Here is a pseudo code that simulates what I'm doing:

```ts
import wretch from "wretch";

interface IUser {
  name: string;
  email: string;
}

const api = wretch().url("https://some-service/api");

export function createUser(user: IUser): Promise<IUser> {
  return api
    .url("/users")
    .post(user)
    .res<IUser>((response) => {
      if (response.status === 204) {
        // do something
      }

      return response.json();
    });
}
```

For some reason, I'm not able to proper type the `.res` block.
With the code above, I get the following error:

```
Argument of type '(response: WretcherResponse) => Promise<any>' is not assignable to parameter of type '(type: WretcherResponse) => IUser'.
  Type 'Promise<any>' is missing the following properties from type 'IUser': name, email
```

I've tried setting the type in many different ways but I can't get ride of the error.
Am I doing something wrong or the type inference is not properly working for this block?

**Comment by elbywan** [comment]
Hey @giulianovarriale,

> Hello. First, thanks for creating this package. Awesome job!

Thanks! 👍 

> Am I doing something wrong or the type inference is not properly working for this block?

Nope, you are not doing anything wrong 😉. Type inference for "thenable" functions was notoriously hard when `wretch` was written, several years ago.

But now, with typescript 4.5+ and the introduction of [the `Awaited` helper](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#the-awaited-type-and-promise-improvements) it is way easier.

I just released a new version which improves the types for `.res` and other parser methods, which should now properly type the sample you posted.

Feel free to reopen otherwise, and thanks for reporting the issue in the first place 🙇.

**Comment by giulianovarriale** [comment]
Wow, that was a quick response and fix!
Nice. I will check if everything works properly.
Thanks for sharing about the new API from typescript btw. Very handy.
