### ISSUE TITLE
More resilient handling of `/` when concatenating urls

### ISSUE THREAD

**Issue by kibertoad** [elbywan/wretch#195]
Currently when one uses `wretch().url('myBaseUrl/');` together with `wretch.get('/my-endpoint)`, this produces URL of `myBaseUrl//my-endpoint`. This throws off mocking solutions, such as `msw`, and request fails.

It would be great to deduplicate `/` when they come from different sources (e. g. base param in `wretch`, .url, .addUrl or call method (.get() etc)), as double `/` is pretty much never what user is actually trying to do in this case.

**Comment by elbywan** [comment]
Hey @kibertoad,

> Currently when one uses wretch().url('myBaseUrl/'); together with wretch.get('/my-endpoint), this produces URL of myBaseUrl//my-endpoint. This throws off mocking solutions, such as msw, and request fails.

This is unfortunate - but expected. Using `.url('myBaseUrl')` instead of `.url('myBaseUrl/')` would be easy enough and prevent any potential issues. Is there any specific reason not to do that?

> It would be great to deduplicate / when they come from different sources (e. g. base param in wretch, .url, .addUrl or call method (.get() etc)), as double / is pretty much never what user is actually trying to do in this case.

Instead of bumping the library size by handling such specific edge cases (not to mention parsing the whole url for every request which would degrade performance a bit), I think that using a very simple middleware would be best suited to the task:

```js
const dedupeSlashMiddleware = next => (url, options) => {
  const _url = new URL(url)
  _url.pathname = _url.pathname.replaceAll("//", "/")
  return next(_url, options)
}

wretch("https://jsonplaceholder.typicode.com/")
  .middlewares([dedupeSlashMiddleware])
  .url("/posts")
  .get()
  .json(console.log)
  .catch(console.error)
```

**Comment by kibertoad** [comment]
@elbywan Main problem is that often this parameter will be different between test, local and prod env, and hence excessive "/" can be caught later than ideal.

As a lighter and easier solution - what do you think by always cutting "/" at the end of any url parameter before storing it? (so that it doesn't have to be done on every request)

**Comment by elbywan** [comment]
> As a lighter and easier solution - what do you think by always cutting "/" at the end of any url parameter before storing it? (so that it doesn't have to be done on every request)

I am not really in favour of this because:
- it would be a breaking change
- having trailing slashes at the end of a segment is a valid use case (`wretch("https://url.com/").url("sub/").url("path")`)

**Comment by kibertoad** [comment]
@elbywan e. g. undici enforces paths always starting with "/", and doing same thing would simplify such cases significantly. adding half of a sub-url sounds like a misuse of the feature.
would be a semver major, yes, but with a better DX

**Comment by elbywan** [comment]
> e. g. undici enforces paths always starting with "/", and doing same thing would simplify such cases significantly. adding half of a sub-url sounds like a misuse of the feature.
would be a semver major, yes, but with a better DX

I humbly disagree, forcing people to write paths starting with `/` instead of being flexible and empower developers does not sound like a better DX to me.

So I am sorry but regarding the original issue I think there are other ways of solving it without:
- breaking things
- preventing other developers having different use cases from using the library

Namely:
- use a very simple middleware
- check if the base url variable has a trailing slash and remove it if so

**Comment by kibertoad** [comment]
make sense! thank you for sharing your perspective on it :)
