### ISSUE TITLE
Hitting timeout that is set - but syntactic sugar not catching it

### ISSUE THREAD

**Issue by lantrix** [elbywan/wretch#37]
Hey there. Loving usage of wretch. So simple to use.

I have a call to an endpoint where it was hitting the timeout, but it was not using the [timeout](https://github.com/elbywan/wretch#timeoutcb-error-wretchererror-originalrequest-wretcher--any) syntactic sugar, but instead being caught by the catch().

```javascript
wretch
  .url(endpoint)
  .formUrl(form)
  .post()
  .setTimeout(8000)
  .timeout(error => console.log('Timeout for ' + endpoint + ' ' + error))
  .json(response => console.log(response)
  .catch(error => console.log('Error: ' + error))
```

The endpoint had started failing as it was being slow. In this case I was getting as below indicating the `.timeout` isn't catching the abort from the 8000ms.

```
Error: AbortError: Aborted for /sdpapi/request?format=json
```

When I bumped the timeout to 20000ms It logged the response. Stupid software upgrade on the target system made it much slower :(

Shouldn't `.timeout()` catch the abort?

**Comment by elbywan** [comment]
Hey @lantrix,

> Hey there. Loving usage of wretch. So simple to use.

Thanks a lot! ❤️  

> The endpoint had started failing as it was being slow. In this case I was getting as below indicating the .timeout isn't catching the abort from the 8000ms.

The function names can be a bit misleading here 😉 .

`.setTimeout` actually uses `AbortController` under the hood that cancels the request from the client side and throw an `AbortError`.
On the other hand, `.timeout` is dedicated to specifically catching the `408 http error code` which is also branded as `TIMEOUT`.

That means that in order to catch the error thrown by `.setTimeout` you actually have to use the [`onAbort`](https://github.com/elbywan/wretch#onabortcb-error-aborterror--any) function.

Hope this will help!

**Comment by lantrix** [comment]
Yeah that makes sense now.

The thing that threw me is the [doco says](https://github.com/elbywan/wretch#timeoutcb-error-wretchererror-originalrequest-wretcher--any) `.timeout` is for `418 I'm a teapot`.

**Comment by elbywan** [comment]
> The thing that threw me is the doco says .timeout is for 418 I'm a teapot.

Ah sorry I'll fix the typo ✍️!
