### ISSUE TITLE
Catchers not found on reusable wretch instance

### ISSUE THREAD

**Issue by tmartensen** [elbywan/wretch#47]
Hey, great library! 

Question: I've set up a reusable `wretch` instance that looks somewhat like the following. Also, I'm having a weird time using `wretch` without having to use `default`, see below:
```javascript
const wretch = require("wretch").default;

const csrfMiddleware = next => (url, opts) => {
  const csrfToken = window.localStorage.getItem("csrfToken");
  opts.headers = { ...opts.headers, "x-csrf-token": csrfToken };
  return next(url, opts);
};

export const apiFetch = wretch()
  .url(`/v1`)
  .accept("application/json")
  .content("application/json")
  .options({
    credentials: "same-origin"
  })
  .middlewares([csrfMiddleware])
  .resolve(resolver => resolver
    .res(response => {
      window.localStorage.setItem("csrfToken", response.headers.get("x-csrf-token"));
      return response.json();
    })
    .catch(error => {
      window.localStorage.setItem("csrfToken", error.response.headers.get("x-csrf-token"));
      throw error;
    })
  );
```

Then, when I try to use the `notFound` catcher in a subsequent call, it errors, saying that the function chain with `notFound` in it is not a function:

```javascript
return apiFetch
  .url(`/foo`)
  .query({
    foo: 'bar'
  })
  .get()
  .notFound(() => {
    return {
      foo: `quux`
    };
  }) // this results in Uncaught TypeError: apiFetch.url(...).query(...).get(...).notFound is not a function
  .then(json => json)
  .catch(error => {
    console.error(error);
  });
```
Any suggestions on the right way to accomplish what I'm doing here?

**Comment by elbywan** [comment]
Hey @tmartensen,

> Hey, great library!

Thanks!

> I'm having a weird time using wretch without having to use default

It's because of the way typescript transpiles default exports to commonjs. I see an `export` in the code, you could just use `import` instead of `require` and it should work.

> Then, when I try to use the notFound catcher in a subsequent call, it errors, saying that the function chain with notFound in it is not a function:

Yes, it's because you are missing a [response type](https://github.com/elbywan/wretch#response-types) in your chain.

```js
return apiFetch
  .url(`/foo`)
  .query({
    foo: 'bar'
  })
  .get()
  .notFound(() => {
    return {
      foo: `quux`
    };
  })
  .json() // <- with this it should work.
  .then(json => json)
  .catch(error => {
    console.error(error);
  });
```

**Comment by tmartensen** [comment]
@elbywan thanks for the quick response! When I try to use an `import` statement, I get this:
`api.js?0361:10 Uncaught TypeError: (0 , _wretch2.default) is not a function`.

Could it be because I'm using a Webpack build and it's picking up the `module` file (dist/index.js) instead of the `main` file (dist/bundle/wretch.js)?

**Comment by elbywan** [comment]
> Could it be because I'm using a Webpack build and it's picking up the module file (dist/index.js) instead of the main file (dist/bundle/wretch.js)?

I think that it's very likely that the error is caused by the bundler config, but on the other hand I'm not sure that the issue is related to the `module` file. 

`dist/index.js` is quite small and the code is pretty standard:

```js
import { Wretcher } from "./wretcher";
var factory = Wretcher.factory;
factory["default"] = Wretcher.factory;
/* Export typescript types */
export { Wretcher } from "./wretcher";
/**
 * Return a fresh Wretcher instance.
 */
export default factory;
//# sourceMappingURL=index.js.map
```

I also tried replicating your problem by using the `getting started` webpack setup, but writing a simple `import` statement was enough to make it work:

`import wretch from 'wretch'`

So unfortunately I don't really know why in your case it fails. :confused:

**Comment by tmartensen** [comment]
@elbywan Thanks for your help! Closing...
