### ISSUE TITLE
Async defer

### ISSUE THREAD

**Issue by edongashi** [elbywan/wretch#55]
Hi! I have read the docs and peeked at the source and I have a few questions.

1. Is `defer` in principle a "managed" (wretcher instead of fetchlike) version of middlewares? It feels much easier to configure the wretcher instead of dotting into the options of middlewares.
2. Can defer be async? I need to attach a token to the request but that token is not available sync (it's lazily fetched the first time a request is made).

I need something like this:

```js
wretch()
  .defer(async w => {
    const token = await this.getAccessToken() // <--- lazy retrieval
    return w.auth('Bearer ' + token)
  })
```

With middleware I have this code (based on your sample code from other issues):

```js
wretch()
  .middlewares([next => async (url, opts) => {
    const token = await this.getAccessToken()
    if (token) {
      return next(url, {
        ...opts,
        headers: {
          ...opts.headers || {},
          Authorization: 'Bearer ' + token
        }
      })
    }

    return next(url, opts)
  }]
```

getAccessToken ensures deduping, caching, refreshing token, etc. So I only need to call this in an async context. With an async defer it would be so simple to write. How feasible is this?

Thanks!

**Comment by elbywan** [comment]
Hi @edongashi,

> Can defer be async?

Well it would be nice indeed, but I'm afraid it's impossible (and a crucial difference between middlewares and defer).

`defer` is called just before performing the fetch request, when calling the http verb method in the chain:

```ts
wretch('...')
   .get() // <- defer is called here implicitly
   .json()
```

Here are the relevant lines in the source code:

```ts
private method(method, options = {}, body = null) {
  /* … */
  baseWretcher = baseWretcher.options({ ...options, method })
  // If _deferredChain was be a chain of Promises, 
  // deferredWretcher would have to wait for their completion and be a Promise itself.
  const deferredWretcher = baseWretcher._deferredChain.reduce((acc: Wretcher, curr) => curr(acc, acc._url, acc._options), baseWretcher)
  return resolver(deferredWretcher)
}
```

The key point is that if `defer` accepted async functions, it would mean that `method()` would 
return a `Promise<...>`.

And this piece of code:

```ts
wretch('...')
  .get()
  .json()
```

Would turn into:

```ts
wretch('...')
  .get()
  .then(w => w.json())
```

Which defeats the purpose of this lib, since it breaks the fluid api.

**Comment by edongashi** [comment]
Aha I see, I was unsure what is called when. It's much clearer now. Thank you for the explanation!
