### ISSUE TITLE
filter duplicate header

### ISSUE THREAD

**Issue by roccomuso** [elbywan/wretch#80]
Since you have a lot of possibilities when gluing together methods you can easily mess up the requests.
I did something like:

```js
wretch(url).headers( 'content-type': 'application/json' ).post(...).json()
// one of these methods added another application/json header
```

and saw that in my requests I had duplicate header: `Content-Type: application/json, application/json`. Causing my server to reject the request.
This shouldn't be possible. Maybe worth filtering duplicate header?

**Comment by elbywan** [comment]
Hi @roccomuso, thanks for reporting the issue 👍 !

`Wretch` stores the headers in using the standard [`Header`](https://developer.mozilla.org/en-US/docs/Web/API/Headers) interface api.

In your example, you are manually appending a lowercase `content-type` key, and then calling `.json({ with_an_object: "argument" })` which appends the same header with a different case (`Content-Type`).

> in my requests I had duplicate header: Content-Type: application/json, application/json

The behaviour when triggering a fetch with a `Header` object containing the same key with different case differs between browsers, Chrome (and I guess that's the one you are using) will concatenate the values (join with a comma separator) whereas Firefox will only use one of the values (and the request will work in that case).

So to me, the bug comes from the browser implementation of `Header` (or maybe a bad specification?) that should not allow setting headers with a different case in the first place.

But anyway, despite that I'll consider checking if a `Content-Type` header is already there and prevent the double entry in the Headers object when calling `.json`  👍.

I will not be able to work on that in the following days as I don't have a lot of free time, but I'll keep the issue open and update the status when I'll be available to work on `wretch` again.

**Comment by roccomuso** [comment]
Thanks for the immediate reply!
In other libs in the past I used to provide lower-case content type and they had it figured out, avoiding any duplication.

But yeah, it worked fine in node.js but got issues in chrome runtime. Better handle the case

**Comment by roccomuso** [comment]
I stumbled again in this issue 1 year later and completely forgot I had encounter this already.
Definetly needs some improvement 🙏🏼

**Comment by jimmed** [comment]
I just stumbled across this issue too, although from the angle of specifying the character set as part of the content-type header.

The API I'm hitting requires us to specify `content-type: application/json; charset=utf-8` otherwise it will consume any request body as ASCII by default, and wretch adds an additional `content-type: application/json` when calling `.json()`.

I love wretch and appreciate you may not have time to address this yourself. I'll take a look at raising a PR for this.

**Comment by jimmed** [comment]
For anybody who needs this, I've written a middleware for fixing my specific variant of this issue, which can be easily adapted as needed:

```ts
import { ConfiguredMiddleware } from 'wretch'
import { Headers, HeadersInit } from 'node-fetch'

const charsetHeaderNames = new Set(['Accept', 'Content-Type'])

export const normalizeCharset =
  (encoding: BufferEncoding = 'utf-8'): ConfiguredMiddleware =>
  (next) => (url, opts) => {
    const headers = new Headers(opts.headers as HeadersInit)

    charsetHeaderNames.forEach((key) => {
      if (!headers.has(key)) return
      const value = headers.get(key) || ''

      const hasCharsetSpecifier = value
        ?.split(/;\s+/g)
        .slice(1)
        .some((part) => part.startsWith('charset='))
      if (hasCharsetSpecifier) return

      headers.delete(key)
      headers.set(key, `${value}; charset=${encoding}`)
    })

    return next(url, {
      ...opts,
      headers: Object.fromEntries(headers),
    })
  }
```

This can then be used as follows:

```ts
wretch().middlewares([normalizeCharset()])
```

The useful part here (to anybody experiencing the OP's issue) is the de-duplication being performed by calling `headers.delete(...)` before `headers.set(...)`.

**Comment by elbywan** [comment]
Since @jimmed provided a great workaround in the form of a middleware (thanks! 🙇) I think this isue can be closed.
